#!/bin/bash

jupyter contrib nbextension install --user
jupyter nbextension enable exercise2/main --sys-prefix

echo "downloading track_information (this may take a while ~144MB!)..."
wget -q -O track_info.pkl "https://uni-muenster.sciebo.de/s/OAGyZIUJiSUQmJK/download"
echo "done!"

echo "downloading event_information..."
wget -q -O event_information.csv "https://uni-muenster.sciebo.de/s/Hlz7wk47CGpu5US/download"
echo "done!"

echo "downloading pp_reference..."
wget -q -O pp_reference.dat "https://uni-muenster.sciebo.de/s/t9Jay6GrvxQOlLl/download"
echo "done!"
